Build: User real source directory inside docker images
MDSplus/mdsplus pull request #1113
Opened 2017-11-07 17:09 UTC by tfredian

The original docker build scripts used /source for the source volume.
Various development tools can be used better if the docker builds use
the same source directory spec as that outside of docker. For example
if the source lives in /home/twf/mdsplus-alpha and that same directory
is used as the internal volume inside the docker container instead of
mapping it to /source, all debug information etc will contain the correct
source file location if used outside of docker.

2017-11-07 18:44 UTC, tfredian commented
retest this please

2017-11-08 10:23 UTC, AndreaRigoni approved these changes
great !

2017-11-08 10:31 UTC, zack-vii commented
actually i would rather recomment an option to the build.sh that may overrider the /source default. this is more transparent an alows for mire freedom.

2017-11-08 10:37 UTC, AndreaRigoni commented
Hi Timo,
 it could be an option but this approach fits well with the same logic of the ./configure script for me.
You wont fire the build.sh outside the source directory for now so the source directory is an implicit information likewise the configure does.

2017-11-08 11:15 UTC, zack-vii commented
No i meant what if you are compiling for a different machine that does not have docker e.g. the source files might be lying elsewhere. i e.g have a link to the sources on each computer so the debugging works fine.
"deploy/build.sh --os=fc25 --test --source-dir=." could do want you want to do but with the same effort you would allow for much more flexibility.
"deploy/build.sh --os=fc25 --test --source-dir=/my/folder/on/target/machine"

2017-11-08 11:47 UTC, zack-vii requested changes

2017-11-08 11:47 UTC, zack-vii commented on deploy/packaging/windows/mdsplus.nsi
> +WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\MDSplus" "InstallSource" "http://www.mdsplus.org/dist${SRCDIR}S/mdsplus${FLAVOR}-${MAJOR}.${MINOR}-${RELEASE}.tgz"
this cant be right

2017-11-08 11:47 UTC, zack-vii commented on deploy/platform/platform_docker_build.sh
> +srcdir=$(realpath $(dirname ${0})/../..)
could be an option passed by build.sh
if [ -z  $srcdir ]
then srcdir=/source
fi

2017-11-08 12:46 UTC, AndreaRigoni commented
Ah now I got your point .. that is because I'm biased by the fact that I don't use the build script very often as I prefer the direct compilation with --with-docker-image parameter

2017-11-08 16:15 UTC, tfredian commented
This pull request will be replaced by a new one.

2017-11-08 16:15 UTC, closed without merging