Gm fix settimecontext
MDSplus/mdsplus pull request #1241
Opened 2018-02-26 15:48 UTC by GabrieleManduchi

There were still cases in which TreeSetTimeConcest() was called with a null dbid, e.g. when called within mdsip. This check avoids crashes in mdsip that occurred using jScope (in turn using SetTimeContext via mdsip). When no dbid is defined, success is returned  (TreeSetTimeContext is void)

2018-02-26 16:18 UTC, zack-vii requested changes
did you read my comment on the issue. if you experience a uninitialized dbid you are either using an old version or you are setting the dbid to null yourself.

2018-02-26 17:45 UTC, AndreaRigoni commented
I added a simple line within the cpp tests that verifies the issue .. it is supposed to work here with the Gab changes and seems to hang the process otherwise.

2018-02-26 20:30 UTC, tfredian commented
I was able to reproduce the hang issue with calling SetTimeContect() in the MdsConnectionTest. I suspect this may be occurring because of the way the mdsip "servers" are being started which is now done using forking of the test itself instead of running mdsip processes. Perhaps the thread locks used in the tree context are getting messed up when the servers are forked from the original test process.

2018-02-27 19:31 UTC, zack-vii commented
replaced by pr #1243 which includes the test and fixes the core problem

2018-02-27 19:31 UTC, closed without merging