Fix:unsigned shorts in MDsDataProvider
MDSplus/mdsplus pull request #1252
Opened 2018-03-07 16:43 UTC by GabrieleManduchi

Added explicit handling of unsigned bytes returned by mdsip evaluation in order to fully use the 8 bit dynamics

2018-03-07 17:13 UTC, zack-vii requested changes
Would the issue not apply to other datatypes as well
SHORT vs USHORT
LONG vs ULONG
etc

2018-03-08 14:00 UTC, GabrieleManduchi commented
Right, just added

2018-03-09 15:33 UTC, GabrieleManduchi commented
Timo,
   could you approve the pull request, if there are no other issues?

2018-03-09 15:34 UTC, zack-vii approved these changes

2018-03-09 15:34 UTC, merged