Gm streaming
MDSplus/mdsplus pull request #1644
Opened 2019-04-08 14:50 UTC by GabrieleManduchi

Added support for data streaming. node.js event_server ptogram will receive data events and send associated samples to Web pages via ServerSentEvent.

2019-04-09 07:23 UTC, zack-vii commented
@GabrieleManduchi : Could you attend the following two things.
1. There seems to be a problem with cpp code:
```log
17:05:11 mdstreeobjects.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl MDSplus::EventStream::run(void) __ptr64" (?run@EventStream@MDSplus@@UEAAXXZ)
17:05:11 \workspace\releasebld\64\bin_x86_64\MdsObjectsCppShr-VS.dll : fatal error LNK1120: 1 unresolved externals
```
2. Could you please rebase your branch.
```git
git fetch upstream/alpha
git rebase  upstream/alpha -i
# check if all good
git push -f
```

2019-04-09 07:27 UTC, GabrieleManduchi commented
retest this please

2019-04-09 08:30 UTC, zack-vii commented
@AndreaRigoni : problem persists

2019-04-09 08:52 UTC, GabrieleManduchi commented
retest this please

2019-04-09 09:18 UTC, GabrieleManduchi commented
retest this please

2019-04-09 09:19 UTC, GabrieleManduchi commented
From console all tests passed, the procedure appears have timed out

2019-04-09 13:18 UTC, tfredian commented
Gabriele the build is failing as Timo mentioned from an undefined reference to the run() method.

00:11:49.228 mdsdataobjects.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl MDSplus::EventStream::run(void) __ptr64" (?run@EventStream@MDSplus@@UEAAXXZ)

I'm far from knowledgeable on c++ but shouldn't the  run method in class EXPORT EventStream:public Event in mdsobjects.h be declared as:

    virtual void run() {}

like it is in class EXPORT Event?

This undefined reference error is happening during the VS build of the dll.

The error can be found at: http://jenkins2.mdsplus.org/job/windows/3142/console

2019-04-09 13:46 UTC, GabrieleManduchi commented
Just removed from Datastreams class

2019-04-09 14:44 UTC, GabrieleManduchi commented
retest this please

2019-04-09 14:45 UTC, GabrieleManduchi commented
......not sure the last test referred to the last push

2019-04-09 20:49 UTC, zack-vii requested changes
I think you should put the EXPORT of EventStream::run back for non WINDOWS_H otherwise you might not be able to use the stream. the last commit was the real fix i think

2019-04-09 20:52 UTC, zack-vii commented on mdsobjects/cpp/datastreams.cpp
> -EXPORT void EventStream::run()
I think you should put the export back for non WINDOWS_H otherwise you might not be able to use the stream

2019-04-10 07:45 UTC, zack-vii commented
can i do one last cleanup and then you may merge it.

2019-04-10 07:49 UTC, zack-vii approved these changes

2019-04-10 08:07 UTC, merged