Fix: acq2106_423 decimation fixes using CULL() when creating the time base dimension segments.
MDSplus/mdsplus pull request #1815
Opened 2019-10-02 21:07 UTC by santorofer

The changes are two fold:
1- To Homogenize the way acq435st.py and acq2106_423st.py deal with the creation of the time dimension segments. We are now using CULL() in both devices.
2- Bring Queue and Empty Python 2 libraries to comply with Python 3 queue library.

2019-10-03 01:32 UTC, WhoBrokeTheBuild requested changes

2019-10-03 01:32 UTC, WhoBrokeTheBuild commented on pydevices/HtsDevices/acq2106_423st.py
> +                        dim_limits=[begin, begin + self.seg_length*dt - 1]
You should compute `begin` from `segment` to avoid floating point issues when you accumulate `begin` over time

2019-10-03 01:53 UTC, zack-vii commented
now I see what you planned on doing with cull. why dont you use the window object instead which was meant for just thid purpose.
```python
from MDSplus import SUBTRACT,DIVIDE,UNARY_MINUS,Window,Range,Dimension
win  = Window(UNARY_MINUS(self.trigger_pre),SUBTRACT(self.trigger_post,1),self.trigger)
rang = Range(None,None,DIVIDE(1.,self.clock))
dim = Dimension(win,rang).setUnits('s')
```
where the self.xxx are nodes of the device.

2019-10-03 16:14 UTC, santorofer commented
Yes, you are right, my mistake. I'll correct it.

2019-10-21 16:52 UTC, joshStillerman commented
Stephen and or Fernando, 
  Can you verify that this latest version gets the right answers ?  The code looks good.

2019-10-25 18:01 UTC, joshStillerman approved these changes
Looks great

2019-10-25 18:11 UTC, WhoBrokeTheBuild approved these changes

2019-10-25 18:13 UTC, merged