Fix: repair python TreeNode.doMethod() method
MDSplus/mdsplus pull request #1830
Opened 2019-10-21 18:42 UTC by tfredian

A change to the python TreeNode implementation broke the doMethod
method. This should fix #1829

2019-10-21 22:04 UTC, zack-vii requested changes
I have to check tomorrow but xd's ref seems to be missing in the args

2019-10-22 12:38 UTC, tfredian commented
Yep, xd.ref was missing from the the arglist. I just added it.

2019-10-22 12:51 UTC, tfredian commented
Hmmm,... this needs some testing. I tried doing a part_name method on a device and it segfaulted.

2019-10-22 13:37 UTC, zack-vii commented
I fixed it today but did not get the chance to commit. will do so in an hour or so

On 22 Oct 2019 14:51, Tom Fredian <notifications@github.com> wrote:

Hmmm,... this needs some testing. I tried doing a part_name method on a device and it segfaulted.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMDSplus%2Fmdsplus%2Fpull%2F1830%3Femail_source%3Dnotifications%26email_token%3DABPRFLU254435JZ47D6OF6TQP3ZODA5CNFSM4JDDEQOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB5TU3I%23issuecomment-544946797&data=02%7C01%7C%7Ce05149a281d74178523b08d756ee98a3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637073455066754161&sdata=GuXi3A3JJ5Gii8vXA3%2FdB9rtSKZJsaBMSLeRGxowI%2Fg%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABPRFLSQYIU2UKUAUS7GD7TQP3ZODANCNFSM4JDDEQOA&data=02%7C01%7C%7Ce05149a281d74178523b08d756ee98a3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637073455066754161&sdata=AkaItgxBOSzWxKfZsYGW3CRp8NvB19w9FilSE0hju2I%3D&reserved=0>.

2019-10-22 14:50 UTC, tfredian commented
oops... I was working on the fix at the same time. In trying to test this with `Tree('subtree',-1).A14.INPUT_1.doMethod('part_name')`
I found some other unexpected results. I'm not sure if the original TreeDoMethod worked with things like part_name but the existing one does not. The part_name method for most of the C based devices uses StrCopyDx which doesn't support an xd for the output. It may not be worth fixing this issue. Not sure how the original part name strings are generated for C devices.

2019-10-22 15:13 UTC, zack-vii commented
no worries, I just had to do a quick fix so a colleague could use mdsplus to do some test shots. my doMethod

```
         arglist=[self.ctx]
         xd=_dsc.descriptor_xd()
        argsobj = [_scr.Int32(self.nid),_scr.String(method),_C.Int32(len(args))]
         argsobj+= list(map(_dat.Data,args))
         arglist+= list(map(_dat.Data.byref,argsobj))
        arglist+= [xd.ref]
        _exc.checkStatus(_TreeShr._TreeDoMethodA(*arglist))
         return xd._setTree(self.tree).value
```

2019-10-22 15:15 UTC, tfredian commented
The original part name code is calling _TreeDoMethod and passes a descriptor_d for the answer so that is still working. Not sure we need to change things for a python doMethod() implementation but I'm not entirely sure why the TreeDoMethodA routines stick the status in the output xd since methods should be able to load an answer in the output xd. The routine itself returns the status so if the status is ok the method implementation is responsible for loading the output xd.

2019-10-22 15:16 UTC, zack-vii commented
it was so it can be used for amy method. returning mdsplus objects. not only status

2019-10-22 15:18 UTC, zack-vii commented
I have to cjeck in _c.Int32 should be _scr.Int32

2019-10-22 15:23 UTC, zack-vii commented
I updated the code

2019-10-22 15:44 UTC, zack-vii commented
it only converst status into xd for c methods as thatvwa the only thing they returned sobfar. we could change that if required. the xd was maily meant for python methods

2019-10-22 15:46 UTC, tfredian commented
You update the code where??? This PR only has commits from me and it seems to work. I only tested it with part_name which uncovered 1) the part name code doesn't work with an xd output and 2) the _TreeDoMethodA implementation overwrites anything put in the xd with the status return of the method call. If I change the macro used by C devices to use MdsCopyDxXd instead of StrCopyDx the contents of the xd in _TreeDoMethodA does contain the string but that immediately gets overwritten with a dtype_long with the status return. I have not tested the handling of args with the _TreeDoMethodA call. Your suggested code in the comment above will not work as _TreeDoMethodA expects to be called with ctx, desc(nid),desc(method),len(nargs),pointer-to-array-descr-ptrs,xd.

2019-10-22 15:47 UTC, zack-vii approved these changes

2019-10-22 15:47 UTC, merged

2019-10-22 15:49 UTC, tfredian commented
As I said it might not be worth "fixing". I suspect there won't be many new C devices implemented if any and I think the only methods in existing C device that returned data was part_name and GetNci is using _TreeDoMethod and passing a descriptor_d for the output and works.

2019-10-22 15:51 UTC, zack-vii commented
we should chsnge the c methods part of TreeDoMethodA to leave xd untouched then. and return status instead if status not ok. basically treat it like py and tdi methods