Fix:Missing tree context in fixup nid in copydx
MDSplus/mdsplus pull request #2046
Opened 2020-06-05 13:26 UTC by GabrieleManduchi

TreePutRecord TreeFixupNid needs also tree context otherwise TreeGetPath() fails whan getting the path of a node in a different subtree. (see issue 2043).  MdsCopyDxXdOutZ has been changed to account for an additional parameter to FixupNid. Subsequent changes around derive from this

2020-06-05 13:29 UTC, GabrieleManduchi commented
Timo, have a look also to the change I had to do in ServerBuildDispatchTable. The previous usage of fixup_nid there was wrong as it declared an int argument, while a pointer argument was passedby CopyDxXdOutZ

2020-06-05 13:42 UTC, GabrieleManduchi commented
Check also the change in TdiGetDbi. Again, the argument for fixup_nid was wrongly declared as int

2020-06-05 13:55 UTC, zack-vii commented
i already left for the weekend. will check it on sunday when i am back home.

2020-06-07 17:33 UTC, zack-vii commented
I dont think we can make that api change, those methods are EXPORTED function so they may be used in user code.  instead we would need to somhow pass the second arg. as part of the first. e.g. is teh arg is usually a descriptor it could be a DTYPE_LIST with ctx and the usual arg1. better would be to have an _fixupd_nid that takes a array of two pointers. and pass the required args in that array

2020-06-07 17:34 UTC, zack-vii requested changes
We connot do an API change

2020-06-07 17:41 UTC, zack-vii requested changes
Can you add a test that fails on current alpha. here in the comments. I will modify the TreeFixupNid to take the required arglist as one arg so the api can be used as is.

2020-06-07 20:54 UTC, zack-vii commented
@GabrieleManduchi : i made an alternative PR the should have the same fix/ but also for Segment and without breaking the API in #2047 . Can you check if this fixes your problem, review it, and close this one, please?

2020-06-08 06:52 UTC, closed without merging