Feature: New acq2106 435ELF transient device
MDSplus/mdsplus pull request #2240
Opened 2021-02-23 07:33 UTC by santorofer

New acq2106_435tr transient device:

1- Add to the acq2106_435st superclass:
- pre-sample and post-sample tree nodes
- trigger source and event0 source tree nodes
2- calibration expression written in the INPUT_xxx nodes
3- add a new parameter to the super-class init() method to be able to select between arming the digitizer when using the streaming device, or the transient device.

2021-03-02 22:06 UTC, santorofer commented
retest this please

2021-03-31 21:13 UTC, santorofer commented
retest this please

2021-04-07 19:29 UTC, WhoBrokeTheBuild requested changes

2021-04-07 19:29 UTC, WhoBrokeTheBuild commented on pydevices/HtsDevices/acq2106_435st.py
> +    def init(self, is_arm=1):
Does `is_arm` mean that it is already armed? Or that we want to arm it?

2021-04-07 19:29 UTC, WhoBrokeTheBuild commented on pydevices/HtsDevices/acq2106_435st.py
> +        if armed_by_transient is False:
`if not armed_by_transient`

2021-04-07 19:29 UTC, WhoBrokeTheBuild commented on pydevices/HtsDevices/acq2106_435tr.py
> +    sites=1
`sites = 1`

2021-08-18 15:30 UTC, zack-vii commented
another one?

2021-11-19 20:51 UTC, santorofer commented on pydevices/HtsDevices/acq2106_435tr.py
> +    sites=1
Done.

2022-01-03 18:37 UTC, santorofer commented on pydevices/HtsDevices/acq2106_435st.py
> +        if armed_by_transient is False:
Done. Thanks.

2022-01-05 17:33 UTC, WhoBrokeTheBuild submitted a review, later dismissed

2022-01-06 02:53 UTC, WhoBrokeTheBuild approved these changes

2022-01-06 02:54 UTC, merged