Gm tree thread
MDSplus/mdsplus pull request #2371
Opened 2021-08-24 14:25 UTC by GabrieleManduchi

A bunch of fixes required because of the recnt chantge in distributed client requesting every thread to open its own tree

2021-08-26 10:15 UTC, zack-vii requested changes

2021-08-26 10:15 UTC, zack-vii commented on pydevices/RfxDevices/MARTE2_COMPONENT.py
> +                       #     dataSourceText += '        SamplePhase = ' + \
lots of these

2021-08-26 10:15 UTC, zack-vii commented on java/jdispatcher/src/main/java/mds/jdispatcher/InfoServer.java
> +System.out.println("End collectAction()");
same here, there is a lot of commented code. anyway. you left some debug prints in.

2021-08-26 10:15 UTC, zack-vii commented on pydevices/RfxDevices/MARTE2_SUPERVISOR.py
> +        return 1
why do you return 1 here.. the device api does not require a status value.. instead we raise MDSplus exceptions in case of an error

2021-08-26 10:15 UTC, zack-vii commented on device_support/national/cRioMPAGfunction.h
> +    float period;
this file could use a clang-format

2021-08-26 10:15 UTC, zack-vii commented on pydevices/RfxDevices/NI6368EV.py
> +        return 1
return 1... there are more of these..

2021-08-26 10:15 UTC, zack-vii commented on pydevices/RfxDevices/NI6368EV.py
> +            return
return at the end of a fuction?   try to write as pep8 conform as possible.. there are good ides out there. spyder,  vscodethat help you find  most issues

2021-08-26 10:44 UTC, GabrieleManduchi commented on pydevices/RfxDevices/MARTE2_COMPONENT.py
> +                       #     dataSourceText += '        SamplePhase = ' + \
Some of them should remain because represents hints on future work, other can go out. I will go through

2021-08-26 10:54 UTC, GabrieleManduchi commented on pydevices/RfxDevices/MARTE2_SUPERVISOR.py
> +        return 1
ok, removed

2021-08-26 12:07 UTC, GabrieleManduchi commented on pydevices/RfxDevices/NI6368EV.py
> +        return 1
ok, reported

2021-08-26 12:07 UTC, GabrieleManduchi commented on pydevices/RfxDevices/NI6368EV.py
> +            return
ok, reported

2021-08-26 12:43 UTC, zack-vii commented on pydevices/RfxDevices/MARTE2_SUPERVISOR.py
> +        self.doState(2)
what does doState5 do.. why does it doState(2).. is this a typo.. maybe a comment about why these methods are useful.
furthermore pythonic methods use [a-z][a-z0-9_]* rather than camel-case

2021-08-26 12:49 UTC, zack-vii commented
test failed because of an external issue


``` 
{
   python dl leak
   Memcheck:Leak
   match-leak-kinds: possible
   fun:malloc
   fun:_dl_map_object_deps
   fun:dl_open_worker
   fun:_dl_catch_exception
   fun:_dl_open
   fun:dlopen_doit
   fun:_dl_catch_exception
   fun:_dl_catch_error
   fun:_dlerror_run
   fun:dlopen@@GLIBC_2.2.5
   obj:/usr/lib64/python3.8/lib-dynload
}
```

2021-08-26 13:00 UTC, GabrieleManduchi commented
retest this please

2021-08-26 13:18 UTC, GabrieleManduchi commented on pydevices/RfxDevices/MARTE2_SUPERVISOR.py
> +        self.doState(2)
typo...

2021-08-26 13:56 UTC, zack-vii submitted a review, later dismissed

2021-08-26 20:55 UTC, zack-vii submitted a review, later dismissed
commented code means unfinished code.. please dont publish unfinished code.

2021-08-26 21:16 UTC, zack-vii approved these changes

2021-08-26 23:18 UTC, zack-vii commented
retest this please

2021-08-26 23:19 UTC, merged

2021-08-27 06:25 UTC, GabrieleManduchi commented
Thanks Timo