In the 423/435 stream devices, dev.copy() was moved back to the main process.
MDSplus/mdsplus pull request #2477
Opened 2022-07-08 16:04 UTC by santorofer

The 423/435 streaming devices contain a call to copy the tree (`dev.copy()`) inside the MDSWorker's new thread. 
This breaks the code when executing it from an mdsip service (i.e. when dispatching the INIT action).
Moving that statement back to the main process thread fixes the issue.

2022-08-01 21:08 UTC, WhoBrokeTheBuild requested changes

2022-08-01 21:08 UTC, WhoBrokeTheBuild commented on pydevices/HtsDevices/acq2106_435st.py
> +            self.nchans     = self.dev.sites * 32
Why 32? Can we put that in a constant or add a comment?

2022-08-01 21:08 UTC, WhoBrokeTheBuild commented on pydevices/HtsDevices/acq2106_435st.py
> +        nchans = self.sites * 32
Same question as above, maybe do a static constant in the class

2022-08-02 21:52 UTC, WhoBrokeTheBuild requested changes

2022-08-02 21:52 UTC, WhoBrokeTheBuild commented on pydevices/HtsDevices/acq2106_423st.py
> +            self.nchans = self.dev.sites * NUM_CHANS_PER_SITE
You still need to use `self.NUM_CHANS_PER_SITE`

2022-08-02 21:52 UTC, WhoBrokeTheBuild commented on pydevices/HtsDevices/acq2106_435st.py
> +            self.nchans     = self.dev.sites * NUM_CHANS_PER_SITE
You will need to use `self.dev.NUM_CHANS_PER_SITE`

2023-04-06 19:43 UTC, WhoBrokeTheBuild commented
We should switch to passing the shot ID and tree name to the child thread, and having it create its own Tree object instead of calling .copy()

2023-04-07 13:21 UTC, WhoBrokeTheBuild requested changes

2023-04-07 13:21 UTC, WhoBrokeTheBuild commented on pydevices/HtsDevices/acq2106_423st.py
> +            self.info = (dev.tree.name, dev.tree.shot, dev.path)
Originally this was made to emulate the to_info and from_info functions that I made for Josh, but we've replaced those with just multiple variables, so I think we should do the same here.
```
self.tree = dev.tree.name
self.shot = dev.tree.shot
self.path = dev.path

...

tree = MDSplus.Tree(self.tree, self.shot)
self.dev = tree.getNode(self.path)
```

2023-04-07 13:25 UTC, santorofer commented on pydevices/HtsDevices/acq2106_423st.py
> +            self.info = (dev.tree.name, dev.tree.shot, dev.path)
Ok, this looks good to me too. I'll make those changes then.

2023-04-07 18:30 UTC, WhoBrokeTheBuild submitted a review, later dismissed

2023-04-07 19:01 UTC, WhoBrokeTheBuild approved these changes

2023-04-07 19:02 UTC, merged