Fix XNCI writes corrupting node data
MDSplus/mdsplus pull request #2498
Opened 2022-11-01 15:22 UTC by WhoBrokeTheBuild

The following code is likely supposed to do something useful, but currently it clobbers the data in a node when you write data into an XNCI.

Steps to reproduce with current alpha:
```py
import MDSplus
tree = MDSplus.Tree('tree', 0)
tree.NODE_NAME.record = 1234
tree.setExtendedAttribute('hello', 'world')
tree.NODE_NAME.record # throws data corrupted exception
```

@zack-vii This code was part of one of your original commits to add / restructure XNCIs, I would love for you to look at this before I remove these lines.

2022-11-15 17:01 UTC, WhoBrokeTheBuild commented
retest this please

2023-10-04 15:10 UTC, WhoBrokeTheBuild commented
@zack-vii Can you please look at this?

2023-10-05 02:24 UTC, joshStillerman commented
How are all these in 1 PR?  A bad merge?Sent from my iPhoneOn Oct 4, 2023, at 11:45 AM, Stephen Lane-Walsh ***@***.***> wrote:﻿
@zack-vii Can you please look at this?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-05-01 19:56 UTC, WhoBrokeTheBuild commented
@zack-vii Just to ping you again, I want to make sure this change is good and the code I'm removing isn't necessary for something else

2024-05-29 23:36 UTC, mwinkel-dev commented
The lines suggested for removal date back to the very early history of the `TreeSegments.c` file.  The third commit made to the file (hash `bd30483` on 29-Jan-2007) contains similar lines.  (Of course the code segment has been refactored a few times over the years.)

[bd30483 excerpt] (https://github.com/MDSplus/mdsplus/blob/bd304834b3c710835dbeae4ac4f76bb09f665915/treeshr/TreeSegments.c#L104C1-L116C6)

Given this long history, there are three possibilities to consider:

1. perhaps this is a latent bug that has been present from 2007, or
2. maybe these lines were needed for a feature that is no longer used, or
3. perhaps these lines are still needed in some scenarios.

It will take time to determine which of those possibilities is true.   Thus, the review of this PR will take some time.

2024-06-01 14:24 UTC, zack-vii commented
in branch zck-xnci I added _TreeSetXnci operations trying to break segmented nodes but that seems to work fine.

2024-06-01 15:02 UTC, zack-vii requested changes
As explained in the comments. I think the issue is rather in TreeGetRecord jumping to wrong conclusions in the existence of extended attributes.

2024-06-01 22:01 UTC, zack-vii commented
I revoke my concern.. it is related to the writing, however we cannot omit clearing the standard record if we are writing segments. i cleaned it up a little. it clears the record now only when writing segments or when updating xncis. This lead no into an alternative solution  #2785 and a few other PRs that fix unrelated issues that i spotted during my inspection  #2782, #2783,  #2784.

2024-06-03 16:00 UTC, mwinkel-dev commented
Hi @zack-vii -- Thanks for looking at this XNCI issue and for the additional PRs.

Stephen asked me to review this PR #2498 a while ago.   I will now compare it to your PRs (and thereby learn a lot more about XNCI stuff).   It will likely take a few days before we have all of the PRs reviewed and approved.

Thanks again for the help with this XNCI issue!

2024-06-03 21:02 UTC, closed without merging