Gm fix apd
MDSplus/mdsplus pull request #2661
Opened 2023-12-11 13:03 UTC by GabrieleManduchi

Added support for handling APD descriptors now returned by Connection.get()

2023-12-13 00:34 UTC, WhoBrokeTheBuild commented
Thanks for working to fix this, could you add some explanation around the changes you made and why?

2023-12-18 19:42 UTC, ModestMC commented
There are a number of file modifications in here that I can't really tell what they're doing (probably wise to check them and make sure they should be included in this specific PR rather than being in their own separate one), but per #2660 I tested whether this at least allows MATLAB to do what it's supposed to and it works correctly.

2023-12-20 20:17 UTC, mwinkel-dev commented
Manually built on Ubuntu 20 and ran the standard test suite.  

- The addition of the new `TreePutDeserialized.fun` caused it to fail the `test-tab.tdi` tests.   However, that is simply because the `tditest/testing/test-tab.ans` output file needs to be updated to include the new function.
- All other automated tests passed.
- Also manually ran the IDL tests and they too passed.

Will now manually experiment with MATLAB to confirm that this PR fixes the issue with signals (i.e., will be repeating the testing that @ModestMC did a few days ago).

2023-12-20 23:10 UTC, mwinkel-dev commented
A simple test using MATLAB R2022a was able to read a signal and plot it.

![image](https://github.com/MDSplus/mdsplus/assets/122583770/90e8f719-e5e8-466a-bebb-d3fc04fd7b49)

2023-12-21 16:47 UTC, mwinkel-dev commented
Also manually built for RHEL8 and ran the automated test suite.   As expected, passed all tests except for `test-tab.tdi`.   Worked fine, just need to update the test (see post two or three above about testing on Ubuntu 20).

Did not test MATLAB on RHEL8.

2024-01-03 21:23 UTC, mwinkel-dev requested changes
As per a recent software team meeting, the `tditest/testing/test-tab.ans` file needs to include the new `TreePutDeserialized.fun` function and then be added to this PR.  This change is needed so that the `test-tab.tdi` test passes.   (Let me know if you wish for me to add the file for you, and if so the best way to do so.)

Although I reviewed the MATLAB portion of this PR (i.e., confirmed that MATLAB can now retrieve signal data), I only glanced at the APD changes.   

Thus, it would be good to have an additional reviewer on this PR.

2024-01-08 07:57 UTC, GabrieleManduchi commented
Josh, could you please have a look and in case approve the PR? Cristian from TCV is waiting for it.....

2024-01-08 13:24 UTC, joshStillerman commented
Yes, I will look at it. An issue is that Stephen is redoing Jenkins and we are not making releases yet.Sent from my iPhoneOn Jan 8, 2024, at 2:58 AM, GabrieleManduchi ***@***.***> wrote:﻿
Josh, could you please have a look and in case approve the PR? Cristian from TCV is waiting for it.....

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-01-10 13:57 UTC, GabrieleManduchi commented
Josh, finally I managed fixing it (really tricky...). Could you approve the PR now?

2024-01-10 14:03 UTC, joshStillerman approved these changes

2024-01-10 14:38 UTC, GabrieleManduchi commented
we still need two more approvals....

2024-01-10 15:03 UTC, WhoBrokeTheBuild commented
One reviewer is enough, but you need to mark the change that Mark requested as complete

2024-01-10 15:07 UTC, WhoBrokeTheBuild approved these changes

2024-01-10 15:13 UTC, mwinkel-dev approved these changes

2024-01-10 15:15 UTC, mwinkel-dev commented
Hi Gabriele -- Thanks for regenerating the `test-tab.ans` file so it now contains the new `TreePutDeserialized` function.

2024-01-10 15:16 UTC, GabrieleManduchi commented
ok, thanks

2024-01-10 15:16 UTC, merged