Fix: treatment of scalars in TdiTrans.c
MDSplus/mdsplus pull request #2832
Opened 2024-11-21 17:54 UTC by merlea

A proposed fix for #2831 with some tests.

2024-12-02 19:27 UTC, joshStillerman commented
retest this please

2025-04-16 19:01 UTC, heidthecamp commented
Retest this please

2025-04-16 20:08 UTC, mwinkel-dev commented on tdishr/TdiTrans.c
> +  aflags_t aflags_default = {0,1,1,0,0};
The `include/mdsdescrip.h` file defines `aflags_t` as a packed bit struct with 6 fields.   However, the default is only initializing 5 fields.   Is this correct?

2025-04-16 22:26 UTC, heidthecamp commented on tdishr/TdiTrans.c
> +  aflags_t aflags_default = {0,1,1,0,0};
This is kind of correct from what I saw. For clarification and to fix a mis alignment I have a commit I plan on pushing tomorrow.

2025-04-18 14:41 UTC, heidthecamp requested changes
This looks really good and I'm excited to see the addition of the tests. Just a few small things.

2025-04-18 14:41 UTC, heidthecamp commented on tdishr/TdiTrans.c
> +  aflags_t aflags_default = {0,1,1,0,0};
I believe this is may be setting the wrong flags.  To fix this and avoid confusion can you change this to be
```c
aflags_t aflags_default = {
    .binscale = 0,
    .redim = 1,
    .column = 1,
    .coeff = 0,
    .bounds = 0,
};
```

2025-04-18 14:41 UTC, heidthecamp commented on tdishr/TdiTrans.c
>        arr.arsize = arr.length;
The additions are good but we some of the things we removed are still required. Can you add back in `a0` and `m[0]`
```c
arr.scale = 0;
arr.digits = 0;
arr.aflags = aflags_default;
arr.a0 = arr.pointer;
arr.dimct = 1;
arr.m[0] = 1;
arr.arsize = arr.length;
```

2025-04-18 14:41 UTC, heidthecamp commented on tdishr/TdiTrans.c
>        arr.arsize = arr.length;
Same comment as above
```c
arr.scale = 0;
arr.digits = 0;
arr.aflags = aflags_default;
arr.a0 = arr.pointer;
arr.dimct = 1;
arr.m[0] = 1;
arr.arsize = arr.length;
```

2025-04-21 14:23 UTC, merlea commented on tdishr/TdiTrans.c
>        arr.arsize = arr.length;
I don't quite understand why. We are setting `arr.aflags.coeff=0` and so `a0` and `m` should not ever be used.

2025-04-23 12:27 UTC, merlea commented on tdishr/TdiTrans.c
> +  aflags_t aflags_default = {0,1,1,0,0};
I updated this one.

2025-04-23 15:02 UTC, WhoBrokeTheBuild commented on tdishr/TdiTrans.c
>        arr.arsize = arr.length;
You're absolutely correct, those fields are not required, but setting them with the correct values is easy and helps make the code more robust. I think they are beneficial to add, but I won't hold up the PR if you don't want to add them.

2025-04-23 16:26 UTC, merlea commented on tdishr/TdiTrans.c
>        arr.arsize = arr.length;
Done. Please check.

2025-04-23 16:26 UTC, merlea commented on tdishr/TdiTrans.c
>        arr.arsize = arr.length;
Done. Please check.

2025-04-23 17:00 UTC, WhoBrokeTheBuild approved these changes

2025-04-23 17:00 UTC, WhoBrokeTheBuild commented
Retest this please

2025-04-24 18:05 UTC, heidthecamp approved these changes

2025-04-24 18:07 UTC, merged