Zck python ctx DO_NOT_MERGE_YET
MDSplus/mdsplus pull request #989
Opened 2017-08-02 02:34 UTC by zack-vii

not deprecation warning yet.
e.g.:
Instead of 
Data.execute(expression_with_node_refs)
one should use
tree_instance.tdi(expression_with_node_refs)

2017-10-12 01:52 UTC, zack-vii commented
TODO: TreeCtx does not properly clean up once the Tree is closed. this caused Windows test to fail as the trees are not closed when they should have been.
TODO2: fishy value: -1for size in _TreeGetRecord->_TreeGetSegmentedRecord->getOpaque_List->TreeGetDsc->malloc(length)
possibly since #1068 in treeshr/TreeSegments.c,359

2017-10-16 11:24 UTC, zack-vii commented
retest this please

2017-10-16 20:00 UTC, tfredian requested changes
compound.py has a try: arg.setTree() except print(arg). Was this for debugging? If so, it should probably be changed.

2017-10-16 20:38 UTC, tfredian approved these changes

2017-10-16 21:43 UTC, merged